@host = http://localhost:3000/api
POST  {{host}}/users
Content-Type: application/json

{
    "email": "mohammedosam1a@ieee.org",
    "username": "mohammedosama"
}
###

POST {{host}}/login
Content-Type: application/json

{
    "email": "mohammedosam1a@ieee.org"
}

###

GET {{host}}/user
Authorization: Bearer {{login.response.body.token}}
