@host = http://localhost:3000/api
POST  {{host}}/users
Content-Type: application/json

{
    "email": "mohammedosam1a@ieee.org",
    "username": "mohammedosama"
}
###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "mohammedosama@ieee.org"
}

###

GET {{host}}/user
Authorization: Bearer {{login.response.body.token}}

###

PUT {{host}}/user/avatar
Authorization: Bearer {{login.response.body.token}}
Content-Type: image/jpeg

< assets/image.jpg

###
GET {{host}}/users?search=mohammed&first=2&after=
Authorization: Bearer {{login.response.body.token}}
###

POST {{host}}/users/mohammedosama/toggle_follow
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama/followers?first=2&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama/followees?first=2&after=
Authorization: Bearer {{login.response.body.token}}
