@host = http://localhost:3000/api
POST  {{host}}/users
Content-Type: application/json

{
    "email": "mohammedosam1a@ieee.org",
    "username": "mohammedosama"
}
###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "mohammedosama@ieee.org"
}

###

GET {{host}}/user
Authorization: Bearer {{login.response.body.token}}

###

PUT {{host}}/user/avatar
Authorization: Bearer {{login.response.body.token}}
Content-Type: image/jpeg

< assets/image.jpg

###
GET {{host}}/users?search=mohammed&first=2&after=
Authorization: Bearer {{login.response.body.token}}
###

POST {{host}}/users/ahmedosama/toggle_follow
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama/followers?first=2&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/ahmedosama/followees?first=2&after=
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/posts
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "content": "Hello there",
    "spoiler_of": "hello",
    "nfsw": true
}

###
GET {{host}}/posts/1
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

###

POST {{host}}/posts/1/toggle_like
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/mohammedosama/posts?before=&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/timeline
Authorization: Bearer {{login.response.body.token}}


###

POST {{host}}/posts/2/comments
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "content": "Hello there"
}

###

GET {{host}}/posts/2/comments?before=&after=
Authorization: Bearer {{login.response.body.token}}

###

POST {{host}}/comments/2/toggle_like
Authorization: Bearer {{login.response.body.token}}


###

GET {{host}}/notifications
Authorization: Bearer {{login.response.body.token}}

###

POST {{host}}/notifications/0/mark_as_read
Authorization: Bearer {{login.response.body.token}}

###

POST {{host}}/mark_notifications_as_read
Authorization: Bearer {{login.response.body.token}}

