DROP DATABASE IF EXISTS go_twitter CASCADE;
CREATE DATABASE IF NOT EXISTS go_twitter;
SET DATABASE = go_twitter;
CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL
)
